# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
environment:
  My_Env_Var1: kalpesh
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
          - checkout
          - run: echo "hello world"       
  build2:
    docker:
      - image: cimg/node:14.10.1
    steps:
          - checkout
          - run: echo $My_Env_Var1
          - run: date; echo '$My_Env_Var1';
          - run: ls -altr  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build2
