# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
environment:
  My_Env_Var1: kalpesh
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:14.10.1
    steps:
          - checkout
          - run: echo "hello world to file" > ~/kk-hw.txt  
          - persist_to_workspace:
              root: ~/ 
              paths:
                - kk-hw.txt
  print_output_file:
    docker:
      - image: circi/node:14.10.1
    steps:
      - attach_workspace:
        at: ~/
    - run: cat ~/output.txt
    
      
  build2:
    docker:
      - image: cimg/node:14.10.1
    steps:
          - checkout
          - run: echo $My_Env_Var1
          - run: date; echo '$My_Env_Var1';
          - run: ls -altr  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build2
      - save_hello_world_output