# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
          - checkout
          - run: echo "hello world"       
  build2:
    docker:
      - image: cimg/node:14.10.1
    steps:
          - checkout
          - run: echo "Welcome Kalpesh"    
          - run: ls -altr  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build2
